services:
  backend:
  # image之後調整
    image: wadandavid/claude_analysis_system:backend-1.1.0
    volumes:
      - ./db:/opt/IEI_claude_using_analysis/db
      - ./data/claude_incoming:/opt/IEI_claude_using_analysis/data/claude_incoming
      - ./data/openai_incoming:/opt/IEI_claude_using_analysis/data/openai_incoming
    restart: unless-stopped
  nginx:
  # image之後調整
    image: wadandavid/claude_analysis_system:nginx-1.1.0
    ports: ["80:80", "443:443"]
    volumes:
      - ./iei_claude.crt:/etc/ssl/certs/iei_claude.crt:ro
      - ./iei_claude.key:/etc/ssl/private/iei_claude.key:ro
    depends_on: [backend]
    restart: unless-stopped